- hosts: localhost
  gather_facts: no
  vars:
    cwd: "{{ lookup('env', 'PWD') }}"
  tasks:
    - name: Get version tag
      command: python -c "import container, sys; sys.stdout.write(container.__version__)"
      register: container_version_result
      tags:
        - always
    - name: Register version tag
      set_fact:
        ansible_container_version: "{{ container_version_result.stdout }}"
      tags:
        - always
    - name: Build pre-baked Conductor bases
      command: python setup.py prebake
      tags:
        - prebake
    - name: Build distribution
      command: python setup.py sdist
      tags:
        - test
        - release
        
